version: 0.0
os: linux
files:
  - source: .
    destination: /temp/test/

hooks:
  AfterInstall:
    - location: scripts/rsync.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/restart_server.sh
      timeout: 300
      runas: root

permissions:
  - object: /tmp/codedeploy
    owner: odoo17
    group: odoo17