version: 0.2

phases:
  install:
    commands:
      - echo Installing necessary dependencies...
      - sudo apt-get update
      - sudo apt-get install -y git

  pre_build:
    commands:
      - echo Cloning repositories...
      - git clone https://github.com/madhukamath29/enterprise_repo.git 
      - git clone https://github.com/madhukamath29/demo-odoo17.git 

  build:
    commands:
      - echo Merging code from both repositories...
      - mkdir merged_code
      - cp -r enterprise_repo/* merged_code/
      - cp -r demo-odoo17/* merged_code/
      - echo Merged code successfully.

  post_build:
    commands:
      - echo Preparing artifacts for deployment...
      - mkdir -p test 
      - cp -r merged_code/* test/
      - ls -l test/
      - echo Artifacts ready....

artifacts:
  files:
    - test/**
  discard-paths: yes

