version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - sudo apt-get update
      - sudo apt-get install -y git

  pre_build:
    commands:
      - echo Starting the pre-build phase...
      - git clonehttps://github.com/madhukamath29/enterprise_repo.git enterprise_repo
      - git https://github.com/madhukamath29/demo-odoo17.git demo-odoo17

  build:
    commands:
      - echo Starting the build phase...
      - mkdir -p merged_code
      - mv merged_code/temp merged_code/temp_backup || true  # Ignore if temp doesn't exist
      - cp -r enterprise_repo/* merged_code/
      - cp -r demo-odoo17/* merged_code/
      - echo Code from enterprise_repo and demo-odoo17 successfully merged into merged_code

  post_build:
    commands:
      - echo Starting the post-build phase...
      - echo Preparing artifacts for CodeDeploy...
      - mkdir -p /tmp/codedeploy  # Ensuring /tmp/codedeploy directory exists
      - cp -r merged_code/* /tmp/codedeploy/
      - echo Artifacts prepared for deployment to EC2.

artifacts:
  files:
    - '**/*'
  discard-paths: no
