version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - sudo apt-get update
      - sudo apt-get install -y git

  pre_build:
    commands:
      - echo Starting the pre-build phase...
      - git clone https://github.com/madhukamath29/enterprise_repo.git 
      - git clone https://github.com/madhukamath29/demo-odoo17.git 

  build:
    commands:
      - echo Starting the build phase...
      - mkdir -p merged_code
      - mv merged_code/temp merged_code/temp_backup || true  # Ignore if temp doesn't exist
      - cp -r enterprise_repo/* merged_code/
      - cp -r demo-odoo17/* merged_code/
      - echo Code from enterprise_repo and demo-odoo17 successfully merged into merged_code

  post_build:
    commands:
      - echo Starting the post-build phase...
      - echo Checking if merged_code has files...
      - test -n "$(ls -A merged_code)" && echo "Files exist in merged_code" || echo "No files in merged_code"
      - echo Listing contents of merged_code...
      - ls -l merged_code
      - echo Preparing artifacts for CodeDeploy...
      - mkdir -p /tmp/codedeploy1  # Ensuring /tmp/codedeploy directory exists
      - echo Copying files from merged_code to /tmp/codedeploy1...
      - cp -r merged_code/* /tmp/codedeploy1/
      - echo Files in /tmp/codedeploy1...
      - ls -l /tmp/codedeploy1/
      - echo Artifacts prepared for deployment to EC2.

artifacts:
  files:
    - '**/*'
  discard-paths: no