version: 0.2

phases:
  install:
    commands:
      - echo "Installing necessary packages..."
      - apt-get update
      - apt-get install -y git

  pre_build:
    commands:
      - echo "Cloning both repositories..."
      - git clone https://github.com/madhukamath29/enterprise_repo.git enterprise_repo
      - git clone https://github.com/madhukamath29/demo-odoo17.git demo_odoo17
      - mkdir -p merged_folder
      - echo "Repositories cloned successfully."

  build:
    commands:
      - echo "Merging both repositories..."
      - cp -r enterprise_repo/* merged_folder/
      - cp -r demo-odoo17/* merged_folder/
      - echo "Repositories merged successfully."

  post_build:
    commands:
      - echo "Deploying merged code to merged_folder..."
      - ls merged_folder
      - echo "Deployment successful."

artifacts:
  files:
    - merged_folder/**/*
