# -*- coding: utf-8 -*-
# Part of BrowseInfo. See LICENSE file for full copyright and licensing details.

{

    "name": "Dental Clinic",
    "version": "0.0.1",
    "currency": 'RUPEES',
    "summary": "Apps basic Dental Clinic Management system",
    "category": "Industry",
    "description": """
    This module is used to manage Dental Clinic
""",

    "depends": ["base", "sale_management", "stock", "account", "project", "stock", "mrp", "purchase"],
    "data": [
        'security/hospital_groups.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'views/emp_view.xml',
        'views/assets.xml',
        'views/login_page.xml',
        'views/main_menu_file.xml',
        'wizard/medical_appointments_invoice_wizard.xml',
        'wizard/create_prescription_invoice_wizard.xml',
        'wizard/create_prescription_shipment_wizard.xml',
        'views/medical_medicament.xml',
        'views/medical_drug_route.xml',
        'wizard/medical_lab_test_create_wizard.xml',
        'wizard/medical_lab_test_invoice_wizard.xml',
        'views/medical_prescription_order.xml',
        'views/medical_directions.xml',
        'views/medical_dose_unit.xml',
        'views/medical_patient_evaluation.xml',
        'views/medical_family_disease.xml',
        'views/medical_inpatient_registration.xml',
        'views/medical_inpatient_medication.xml',
        'views/medical_insurance_plan.xml',
        'views/medical_appointment.xml',
        'views/medical_insurance.xml',
        'views/medical_patient_lab_test.xml',
        'views/medical_lab_test_units.xml',
        'views/medical_lab.xml',
        'views/medical_neomatal_apgar.xml',
        'views/medical_pathology_category.xml',
        'views/medical_pathology_group.xml',
        'views/medical_pathology.xml',
        'views/medical_patient_disease.xml',
        'views/medical_patient_medication.xml',
        'views/medical_patient_medication1.xml',
        'views/medical_patient_pregnancy.xml',
        'views/medical_patient_prental_evolution.xml',
        'views/medical_patient.xml',
        'views/medical_physician.xml',
        'views/medical_preinatal.xml',
        'views/medical_prescription_line.xml',
        'views/medical_puerperium_monitor.xml',
        'views/medical_rcri.xml',
        'views/medical_rounding_procedure.xml',
        'views/medical_test_critearea.xml',
        'views/medical_test_type.xml',
        'views/medical_vaccination.xml',
        'views/res_partner.xml',
        'views/treatment_plan_wizard.xml',
        'views/medical_treatment_stages_views.xml',
        'views/medicine_form.xml',
        'views/medicine_test.xml',
        'report/report_view.xml',
        'report/appointment_recipts_report_template.xml',
        'report/medical_view_report_document_lab.xml',
        'report/medical_view_report_lab_result_demo_report.xml',
        'report/newborn_card_report.xml',
        'report/patient_card_report.xml',
        'report/patient_diseases_document_report.xml',
        'report/patient_medications_document_report.xml',
        'report/patient_vaccinations_document_report.xml',
        'report/prescription_demo_report.xml',
        'report/report_medical_tooth.xml',
        'report/medical_apt_inv.xml',
        'report/medical_sale_order.xml',
        'report/medical_purchase_report.xml',

    ],
    "author": "BrowseInfo",
    "website": "https://www.browseinfo.com",
    "installable": True,
    "application": True,
    "auto_install": False,
    "images": ["static/description/Banner.gif"],
    "live_test_url": 'https://youtu.be/fk9dY53I9ow',
    "license": 'OPL-1',

}

# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
